### ISSUE TITLE
Infinite recursion with jitter in certain cases

### ISSUE THREAD

**Issue by dkasak** [MarkusTeufelberger/afl-ddmin-mod#4]
I found another bug but I'm not sure how to fix it cleanly this time. I'm also unsure whether jitter is essential for triggering it but I've been unable to trigger it without it. Unfortunately, I cannot produce a test case for you easily.

The bug happens because `RESULTS` ends up in `ddmin2_mod` as `[((0, 62),)]` (the whole file is of size 128), which afl-ddmin-mod registers as a subset:

    SUBSET FOUND, new best size: 62

This chunk is then split up in many more chunks:

    [((0, 31), (31, 62)), ((0, 32), (32, 62)), ((0, 30), (30, 62)), ((0, 33), (33, 62)), ((0, 29), (29, 62)), ((0, 34), (34, 62)), ((0, 28), (28, 62)), ((0, 35), (35, 62)), ((0, 27), (27, 62)), ((0, 36), (36, 62)), ((0, 26), (26, 62)), ((0, 37), (37, 62)), ((0, 25), (25, 62)), ((0, 38), (38, 62)), ((0, 24), (24, 62)), ((0, 39), (39, 62)), ((0, 23), (23, 62)), ((0, 40), (40, 62)), ((0, 22), (22, 62)), ((0, 41), (41, 62)), ((0, 21), (21, 62)), ((0, 42), (42, 62)), ((0, 20), (20, 62)), ((0, 43), (43, 62)), ((0, 19), (19, 62)), ((0, 44), (44, 62)), ((0, 18), (18, 62)), ((0, 45), (45, 62)), ((0, 17), (17, 62)), ((0, 46), (46, 62)), ((0, 16), (16, 62)), ((0, 47), (47, 62)), ((0, 15), (15, 62)), ((0, 48), (48, 62)), ((0, 14), (14, 62)), ((0, 49), (49, 62)), ((0, 13), (13, 62)), ((0, 50), (50, 62)), ((0, 12), (12, 62)), ((0, 51), (51, 62)), ((0, 11), (11, 62)), ((0, 52), (52, 62)), ((0, 10), (10, 62)), ((0, 53), (53, 62)), ((0, 9), (9, 62)), ((0, 54), (54, 62)), ((0, 8), (8, 62)), ((0, 55), (55, 62)), ((0, 7), (7, 62)), ((0, 56), (56, 62)), ((0, 6), (6, 62)), ((0, 57), (57, 62)), ((0, 5), (5, 62)), ((0, 58), (58, 62)), ((0, 4), (4, 62)), ((0, 59), (59, 62)), ((0, 3), (3, 62)), ((0, 60), (60, 62)), ((0, 2), (2, 62)), ((0, 61), (61, 62)), ((0, 1), (1, 62)), ((0, 62),)]

And then `ddmin2_mod` is called recursively. Inside this call, `RESULTS` becomes `[((0, 62),)]` again and the process continues ad infinitum (or at least until Python's maximum recursion depth is exceeded).

I'm unsure how to proceed. It seems that one possible solution would be to check whether `[(min_(chunklist), max_(chunklist))] == best_result` (where `min_` and `max_` are like Python's `min` and `max` but flatten the chunklist completely) and return early if that condition is true. In other words, check whether `best_result` is a single tuple which spans the whole chunklist. I'm not sure whether that is correct, though.

**Comment by MarkusTeufelberger** [comment]
That seems like a quite extreme case of jitter being applied, also apparently the best possible chunk in this case seems to be (0, 62) anyways, as all other splits must fail for this one to succeed.

While I would not recommend these high jitter settings (it quickly degrades into O(2 * length²) territory) anyways, it still seems to be a bug.

This can't happen in the original ddmin algorithm - at every step the file is split in >1 parts. Probably it is enough to not add splits that span the full chunk length, but require that they are always split in 2 or have a length of exactly 1.

For example:

    >>> split_chunks(((0, 2),), 50)
    [((0, 1), (1, 2)), ((0, 2),)]

should probably just return

    >>> split_chunks(((0, 2),), 50)
    [((0, 1), (1, 2))]

but

    >>> split_chunks(((0, 1),), 50)

should maybe still return

    [((0, 1),)]

to preserve single byte chunks.
